name: train gcp
on: [push]

jobs:
  start-instance:
    env:
      PROJECT_ID: ${{ secrets.GCE_PROJECT }}
      GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
      GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - name: authenticate
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: create runner
        uses: related-sciences/gce-github-runner@v0.4


  core:
    needs: start-instance
    runs-on: ${{ needs.start-instance.outputs.label }}
    steps:
      - uses: actions/checkout@v3

      - name: set up environment
        uses: actions/setup-python@v4

      - name: install dependencies
        run: |
          make install

      - name: Lint
        run: |
          make lint

      - name: Testing
        run: |
          make test


  stop-instance:
    needs:
      - start-instance
      - core
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: stop runner
        uses: related-sciences/gce-github-runner@v0.4
        with:
         command: stop