name: train_aws

on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  deploy-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ${{ secrets.EC2_IMAGE_ID }}
          ec2-instance-type: t2.micro
          subnet-id: ${{ secrets.SUBNET_ID }}
          security-group-id: ${{ secrets.SECURITY_GROUP_ID }}
          aws-resource-tags: > 
            [
              {"Key": "Name", "Value": "ec2-github-runner-${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]
# ---------------------------------------------- End Create runner

# ---------------------------------------------- Main job(s)
  train:
    needs: deploy-runner
    runs-on: "${{ needs.deploy-runner.outputs.label }}"
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v3

      - name: Setup python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install make
        run: |
          sudo apt -y install make && sudo apt -y install build-essential
          

      - name: install dependencies
        run: |
          make install

      - name: Lint
        run: |
          make lint

      - name: Testing
        run: |
          make test

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - deploy-runner
      - train
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.deploy-runner.outputs.label }}
          ec2-instance-id: ${{ needs.deploy-runner.outputs.ec2-instance-id }}
