name: train gcp
on: [push]

jobs:
  start-instance:
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      PROJECT_ID: ${{ secrets.GCE_PROJECT }}
      GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
      GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}
      GCP_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: 'auth'
        name: authenticate
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCE_SA_KEY }}'

      - name: create runner
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: ${{ secrets.GCE_INSTANCE }}
          zone: ${{ secrets.GCE_INSTANCE }}
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: 'echo Hello world'


  core:
    needs: start-instance
    runs-on: ${{ needs.start-instance.outputs.label }}
    steps:
      - uses: actions/checkout@v3

      - name: set up environment
        uses: actions/setup-python@v4

      - name: install dependencies
        run: |
          make install

      - name: Lint
        run: |
          make lint

      - name: Testing
        run: |
          make test


  stop-instance:
    needs:
      - start-instance
      - core
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: stop runner
        uses: related-sciences/gce-github-runner@v0.4
        with:
         command: stop